apiVersion: v2
name: application-application
description: "Helm Chart for deploying {{application}} on k8s"
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common-helpers
    repository: oci://ghcr.io/webgrip/common-charts
    version: 1.0.13
