name: "[Maint] Keep development in sync with main"
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  ff:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0

      - name: Fast-forward development to main
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin main
          if git merge --ff-only origin/main; then
            git push origin HEAD:development
          else
            echo "Diverged; skipping to preserve required_linear_history."
          fi